class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
  # ensures that the request received is in fact coming from the session of the authorized user, To make  this happen protect_from_forgery will automatically include a security token(HIDDEN ID), calculated from the current session and the server-side secret, in all the forms and Ajax requests generated by Rails.

  # Force signout to prevent CSRF attacks
  def handle_unverified_request
    sign_out
    super
    #When you invoke super with no arguments Ruby sends a message to the parent of the current object, asking it to invoke a method of the same name as the method invoking super. It automatically forwards the arguments that were passed to the method from which it's called.
  end
end
